export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <div>{children}</div>;
}
