name: deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print GitHub Actions IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - name: Add GitHub Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.PROD_AWS_SG_ID }} \
          --protocol tcp --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32
