name: deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Dependencies
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: npm-package-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-package-${{ hashFiles('**/package-lock.json') }}
            npm-package-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_PASSWORD }}
          aws-region: ap-southeast-2

      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print GitHub Actions IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - name: Add GitHub Actions IP to AWS Security group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.AWS_SG_ID }} \
          --protocol tcp --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32 \

      - name: Deploy to AWS Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_KEY }}
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          script: |
            cd ~/src/blog_dev_v1
            git pull origin main
            npm run docs:build
            sudo rm -rf /var/www/dist
            sudo cp -r ./.vitepress/dist /var/www/dist
            sudo service nginx restart
